version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling Java code...
      - ./gradlew bootJar
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/aws-gradle.jar